name: Run Tests on Pull Request

on:
  pull_request:
    branches: [ train_model ]
  workflow_dispatch:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3 # Stop work flow after x minnutes, the job will continue to run in kaggle
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Execute Kaggle Script Action
        uses: KevKibe/kaggle-script-action@v1.0.5
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: "Run Unit Tests Public run"
          custom_script: |
                pytest test.py

          enable_internet: true
          enable_gpu: false
          enable_tpu: false
          sleep_time: 10
      - name: Stop workflow if tests succeed or fail
        if: always()  # Ensures this runs regardless of success or failure
        run: exit 0   # stop workflow
